[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
  external_node_modules = ["square"]
  included_files = ["netlify/functions/**/*"]

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

[[redirects]]
  from = "/webhook/*"
  to = "/.netlify/functions/square-webhook"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"